baseurl = "/"
canonifyurls = true
disqusShortname = "spf13"
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
theme = "hugo-theme-casper"
title = "Casper Theme"
[params]
author = "Art Res"
authorlocation = "USA"
authorwebsite = "https://artres.xyz"
bio = "I love art, science, and technology. "
cover = "images/cover.jpg"
description = "Lovely demo site!"
githubname = "akufta"
googleanalyticsuserid = "UA-79101-12"
hidehugosupport = false
logo = "images/logo.png"
rsslink = "http://feeds.feedburner.com/..."
twittername = "astrikosart"
[params.social]
twitter = "your_twitter"
